<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Identity.MongoDbCore" Version="3.1.2" />
    <PackageReference Include="MongoDB.Bson" Version="2.30.0" />
    <PackageReference Include="MongoDB.Driver" Version="2.30.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Event lib\Modules.EventLib.csproj" />
    <ProjectReference Include="..\User lib\Modules.UserLib.csproj" />
  </ItemGroup>

</Project>
