<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>User_lib</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.Identity.MongoDbCore" Version="3.1.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
		<PackageReference Include="MongoDB.Bson" Version="2.30.0" />
		<PackageReference Include="MongoDB.Driver" Version="2.30.0" />
		<PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
	</ItemGroup>

</Project>
