<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="3.1.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\User lib\Modules.UserLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Modules.EventLib">
      <HintPath>..\Event lib\bin\Debug\net8.0\Modules.EventLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
